
// 定义的错误类型码
export enum ExceptionType {
  ERROR_MAI = 'ERROR_MAI',
  ERROR_RUNTIME = 'ERROR_RUNTIME',
  ERROR_RUNTIME_PROMISE = 'ERROR_RUNTIME_PROMISE',
  ERROR_STATIC = 'ERROR_STATIC',
  ERROR_CONSOLE = 'ERROR_CONSOLE',
  ERROR_TRY_CATHC = 'ERROR_TRY_CATHC'
}